import React from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@tauri-apps/api/core';
import './styles.css';
import { useStudio } from './store';

type HFModel={id:string;author:string;downloads?:number;likes?:number;pipeline_tag?:string;tags?:string[]};
const nav=[['dashboard','داشبورد'],['hardware','سخت‌افزار'],['models','مدل‌ها'],['downloads','دانلودها'],['runtime','Runtime'],['chat','گفتگو'],['benchmark','بنچمارک'],['settings','تنظیمات']];
const cards=[['🖥️','سخت‌افزار','تحلیل CPU، RAM، GPU و Backend'],['🧠','مدل‌ها','جستجو و ارزیابی مدل‌های Hugging Face'],['⚡','Runtime','تشخیص و مدیریت llama.cpp'],['⬇️','دانلودها','مدیریت وضعیت دانلود و اعتبارسنجی']];

function App(){
 const {page,setPage,hardware,scan,models,running}=useStudio();
 const title=nav.find(([id])=>id===page)?.[1]||'LocalAI Studio';
 return <div className="app" dir="rtl"><aside><div className="brand">◈ <span>LocalAI Studio</span></div>{nav.map(([id,t])=><button className={page===id?'nav active':'nav'} onClick={()=>setPage(id)} key={id}>{t}</button>)}</aside><main>
 <header><div><small>پلتفرم هوشمند اجرای مدل محلی</small><h1>{title}</h1></div><button className="scan" onClick={scan}>↻ اسکن سخت‌افزار</button></header>
 {page==='dashboard'&&<Dashboard hardware={hardware} running={running} setPage={setPage}/>} 
 {page==='hardware'&&<Hardware hardware={hardware} scan={scan}/>} 
 {page==='models'&&<Models models={models}/>} 
 {page==='downloads'&&<Downloads/>}
 {page==='runtime'&&<Runtime/>}
 {page==='chat'&&<Chat running={running}/>} 
 {page==='benchmark'&&<Benchmark/>}
 {page==='settings'&&<Settings/>}
 </main></div>
}
function Dashboard({hardware,running,setPage}:{hardware:any;running:string;setPage:(p:string)=>void}){return <><section className="hero"><div><span className="pill">آفلاین‌محور · امن</span><h2>هوش مصنوعی محلی، متناسب با سیستم شما</h2><p>LocalAI Studio سخت‌افزار را بررسی می‌کند، مدل مناسب را پیدا می‌کند و اجرای محلی را از یک رابط ساده مدیریت می‌کند.</p><button onClick={()=>setPage('models')}>کشف مدل‌ها ←</button></div><div className="orb">AI</div></section><div className="grid">{cards.map(c=><div className="card" key={c[1]}><b>{c[0]}</b><h3>{c[1]}</h3><p>{c[2]}</p></div>)}</div><section className="panel"><div className="panel-head"><h2>وضعیت سیستم</h2><span className="status-dot">● آماده</span></div><div className="stats"><div>CPU<strong>{hardware.cpu}</strong></div><div>RAM<strong>{hardware.ram}</strong></div><div>GPU<strong>{hardware.gpu}</strong></div><div>مدل فعال<strong>{running||'هیچ مدلی اجرا نیست'}</strong></div></div></section></>}
function Hardware({hardware,scan}:{hardware:any;scan:()=>void}){return <section className="panel"><div className="panel-head"><h2>پروفایل سخت‌افزار</h2><button onClick={scan}>اسکن مجدد</button></div><div className="stats"><div>پردازنده<strong>{hardware.cpu}</strong></div><div>حافظه<strong>{hardware.ram}</strong></div><div>گرافیک<strong>{hardware.gpu}</strong></div><div>Backend<strong>{hardware.backend}</strong></div></div><div className="notice">مقادیر GPU/VRAM در صورت پشتیبانی سیستم‌عامل از ابزارهای تشخیص، به‌صورت واقعی خوانده می‌شوند؛ عدد تخمینی به‌عنوان واقعیت نمایش داده نمی‌شود.</div></section>}
function Models({models}:{models:any[]}){const[q,setQ]=React.useState('');const[remote,setRemote]=React.useState<HFModel[]>([]);const[loading,setLoading]=React.useState(false);const search=async()=>{setLoading(true);try{const r=await fetch('https://huggingface.co/api/models?search='+encodeURIComponent(q||'text-generation')+'&sort=downloads&direction=-1&limit=12');setRemote(await r.json())}catch{setRemote([])}finally{setLoading(false)}};return <section className="panel"><div className="panel-head"><div><h2>مدل‌ها</h2><p>جستجوی زنده در Hugging Face یا مدل‌های محلی ثبت‌شده.</p></div><button onClick={search}>{loading?'در حال جستجو…':'جستجو در Hugging Face'}</button></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="مثلاً Qwen، Llama، coding..."/>{remote.length>0&&<><h3>نتایج Hugging Face</h3>{remote.map(m=><div className="model" key={m.id}><div><b>{m.id}</b><p>{m.pipeline_tag||'مدل عمومی'} · دانلود: {formatNumber(m.downloads||0)} · پسندیده: {formatNumber(m.likes||0)}</p></div><span className="tag">منبع زنده</span></div>)}</>}{remote.length===0&&models.map(m=><div className="model" key={m.id}><div><b>{m.name}</b><p>{m.task} · {m.quant} · {m.size}</p></div><span className="good">{m.score}% سازگاری</span><button onClick={()=>useStudio.getState().run(m.name)}>اجرا</button></div>)}</section>}
function formatNumber(n:number){return new Intl.NumberFormat('fa-IR',{notation:'compact'}).format(n)}
function Downloads(){return <section className="panel"><h2>مدیریت دانلود</h2><div className="empty">هنوز دانلود فعالی وجود ندارد.<br/><small>پس از اتصال Download Manager، وضعیت، سرعت، ETA، Resume و اعتبارسنجی فایل‌ها در اینجا نمایش داده می‌شود.</small></div></section>}
function Runtime(){const[runtimes,setRuntimes]=React.useState<any[]>([]);React.useEffect(()=>{invoke<any[]>('runtime_status').then(setRuntimes).catch(()=>setRuntimes([]))},[]);return <section className="panel"><div className="panel-head"><div><h2>Runtime Manager</h2><p>Runtimeهای نصب‌شده روی سیستم را بررسی می‌کند.</p></div></div>{runtimes.length?runtimes.map(r=><div className="runtime" key={r.id}><div><b>{r.id}</b><p>{r.installed?'نصب شده':'نصب نشده'} · {r.healthy?'سالم':'نیازمند بررسی'}</p></div><span className={r.healthy?'good':'warn'}>{r.healthy?'سالم':'بررسی'}</span></div>):<div className="empty">اطلاعات Runtime در دسترس نیست.</div>}</section>}
function Chat({running}:{running:string}){const[txt,setTxt]=React.useState('');const[msgs,setMsgs]=React.useState<{role:string;text:string}[]>([]);const send=(e:React.FormEvent)=>{e.preventDefault();if(!txt.trim())return;setMsgs(v=>[...v,{role:'user',text:txt.trim()},{role:'system',text:running?`مدل «${running}» انتخاب شده است؛ اتصال Inference Engine در حال تکمیل است.`:'ابتدا یک مدل را اجرا کنید. Runtime فعال پیدا نشد.'}]);setTxt('')};return <section className="panel chat"><div className="panel-head"><div><h2>گفتگو</h2><p>{running?`مدل فعال: ${running}`:'مدل فعالی انتخاب نشده است.'}</p></div></div><div className="messages">{msgs.length===0&&<div className="empty">پیام خود را ارسال کنید. برای اجرای واقعی باید Runtime سالم و مدل معتبر در دسترس باشد.</div>}{msgs.map((m,i)=><div className={m.role==='user'?'user':'ai'} key={i}>{m.text}</div>)}</div><form onSubmit={send}><input value={txt} onChange={e=>setTxt(e.target.value)} placeholder="پیام خود را بنویسید..."/><button>ارسال</button></form></section>}
function Benchmark(){return <section className="panel"><h2>بنچمارک</h2><p>پس از اجرای مدل، این بخش برای اندازه‌گیری load time، tokens/s، RAM و VRAM استفاده می‌شود.</p><div className="stats"><div>Tokens/s<strong>—</strong></div><div>Prompt tok/s<strong>—</strong></div><div>Load time<strong>—</strong></div><div>Peak RAM<strong>—</strong></div></div></section>}
function Settings(){return <section className="panel"><h2>تنظیمات</h2><div className="settings"><label>زبان رابط<select defaultValue="fa"><option value="fa">فارسی</option><option value="en">English</option></select></label><label>ظاهر<select defaultValue="system"><option value="system">همگام با سیستم</option><option value="dark">تیره</option><option value="light">روشن</option></select></label><label>پورت API<input defaultValue="1234" /></label><label>آدرس مدل‌ها<input placeholder="پوشه ذخیره‌سازی مدل‌ها" /></label></div><div className="notice">API به‌صورت پیش‌فرض فقط روی localhost فعال خواهد شد.</div></section>}

createRoot(document.getElementById('root')!).render(<App/>);
